// <auto-generated />
using System;
using AntiqueBookstore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AntiqueBookstore.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<int?>("DeathYear")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LastName", "FirstName");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "British writer",
                            BirthYear = 1859,
                            DeathYear = 1930,
                            FirstName = "Arthur",
                            LastName = "Conan Doyle"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Japanese novelist and poet of the Heian period",
                            BirthYear = 978,
                            DeathYear = 1016,
                            FirstName = "Murasaki",
                            LastName = "Shikibu"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Chinese writer, considered the founder of modern Chinese literature",
                            BirthYear = 1881,
                            DeathYear = 1936,
                            FirstName = "Lu",
                            LastName = "Xun"
                        },
                        new
                        {
                            Id = 4,
                            Bio = "Egyptian writer who won the Nobel Prize for Literature",
                            BirthYear = 1911,
                            DeathYear = 2006,
                            FirstName = "Naguib",
                            LastName = "Mahfouz"
                        },
                        new
                        {
                            Id = 5,
                            Bio = "Nigerian novelist, poet and critic",
                            BirthYear = 1930,
                            DeathYear = 2013,
                            FirstName = "Chinua",
                            LastName = "Achebe"
                        },
                        new
                        {
                            Id = 6,
                            Bio = "Argentine short-story writer, essayist and poet",
                            BirthYear = 1899,
                            DeathYear = 1986,
                            FirstName = "Jorge Luis",
                            LastName = "Borges"
                        },
                        new
                        {
                            Id = 7,
                            Bio = "Russian writer, physician and playwright",
                            BirthYear = 1891,
                            DeathYear = 1940,
                            FirstName = "Mikhail",
                            LastName = "Bulgakov"
                        },
                        new
                        {
                            Id = 8,
                            Bio = "Irish novelist, short story writer and poet",
                            BirthYear = 1882,
                            DeathYear = 1941,
                            FirstName = "James",
                            LastName = "Joyce"
                        },
                        new
                        {
                            Id = 9,
                            Bio = "Colombian novelist and Nobel Prize winner",
                            BirthYear = 1927,
                            DeathYear = 2014,
                            FirstName = "Gabriel",
                            LastName = "García Márquez"
                        },
                        new
                        {
                            Id = 10,
                            Bio = "Italian novelist, literary critic and philosopher",
                            BirthYear = 1932,
                            DeathYear = 2016,
                            FirstName = "Umberto",
                            LastName = "Eco"
                        },
                        new
                        {
                            Id = 11,
                            Bio = "Bengali polymath and Nobel Prize winner",
                            BirthYear = 1861,
                            DeathYear = 1941,
                            FirstName = "Rabindranath",
                            LastName = "Tagore"
                        });
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConditionId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImagePath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("PublicationDate")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("PurchasePrice")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9, 2)");

                    b.Property<decimal?>("RecommendedPrice")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9, 2)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ConditionId");

                    b.HasIndex("StatusId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConditionId = 3,
                            PublicationDate = 1887,
                            Publisher = "Ward Lock & Co",
                            PurchasePrice = 150.00m,
                            RecommendedPrice = 750.00m,
                            StatusId = 2,
                            Title = "A Study in Scarlet"
                        },
                        new
                        {
                            Id = 2,
                            ConditionId = 2,
                            PublicationDate = 1021,
                            Publisher = "Imperial Court of Japan",
                            PurchasePrice = 3500.00m,
                            RecommendedPrice = 12000.00m,
                            StatusId = 1,
                            Title = "The Tale of Genji"
                        },
                        new
                        {
                            Id = 3,
                            ConditionId = 1,
                            PublicationDate = 1918,
                            Publisher = "New Youth Magazine",
                            PurchasePrice = 800.00m,
                            RecommendedPrice = 2500.00m,
                            StatusId = 1,
                            Title = "A Madman's Diary"
                        },
                        new
                        {
                            Id = 4,
                            ConditionId = 2,
                            PublicationDate = 1956,
                            Publisher = "American University in Cairo Press",
                            PurchasePrice = 450.00m,
                            RecommendedPrice = 1800.00m,
                            StatusId = 1,
                            Title = "The Cairo Trilogy: Palace Walk"
                        },
                        new
                        {
                            Id = 5,
                            ConditionId = 3,
                            PublicationDate = 1958,
                            Publisher = "William Heinemann Ltd.",
                            PurchasePrice = 1200.00m,
                            RecommendedPrice = 4500.00m,
                            StatusId = 1,
                            Title = "Things Fall Apart"
                        },
                        new
                        {
                            Id = 6,
                            ConditionId = 1,
                            PublicationDate = 1944,
                            Publisher = "Editorial Sur",
                            PurchasePrice = 900.00m,
                            RecommendedPrice = 3200.00m,
                            StatusId = 1,
                            Title = "Ficciones"
                        },
                        new
                        {
                            Id = 7,
                            ConditionId = 2,
                            PublicationDate = 1967,
                            Publisher = "YMCA Press",
                            PurchasePrice = 1500.00m,
                            RecommendedPrice = 5800.00m,
                            StatusId = 1,
                            Title = "The Master and Margarita"
                        },
                        new
                        {
                            Id = 8,
                            ConditionId = 2,
                            PublicationDate = 1922,
                            Publisher = "Shakespeare and Company",
                            PurchasePrice = 4800.00m,
                            RecommendedPrice = 18000.00m,
                            StatusId = 1,
                            Title = "Ulysses"
                        },
                        new
                        {
                            Id = 9,
                            ConditionId = 1,
                            PublicationDate = 1967,
                            Publisher = "Editorial Sudamericana",
                            PurchasePrice = 1200.00m,
                            RecommendedPrice = 4500.00m,
                            StatusId = 1,
                            Title = "One Hundred Years of Solitude"
                        },
                        new
                        {
                            Id = 10,
                            ConditionId = 1,
                            PublicationDate = 1980,
                            Publisher = "Bompiani",
                            PurchasePrice = 600.00m,
                            RecommendedPrice = 2200.00m,
                            StatusId = 1,
                            Title = "The Name of the Rose"
                        },
                        new
                        {
                            Id = 11,
                            ConditionId = 3,
                            PublicationDate = 1912,
                            Publisher = "India Society of London",
                            PurchasePrice = 2200.00m,
                            RecommendedPrice = 7500.00m,
                            StatusId = 1,
                            Title = "Gitanjali"
                        });
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.BookAuthor", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 2
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 3
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 4
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 5
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 6
                        },
                        new
                        {
                            BookId = 7,
                            AuthorId = 7
                        },
                        new
                        {
                            BookId = 8,
                            AuthorId = 8
                        },
                        new
                        {
                            BookId = 9,
                            AuthorId = 9
                        },
                        new
                        {
                            BookId = 10,
                            AuthorId = 10
                        },
                        new
                        {
                            BookId = 11,
                            AuthorId = 11
                        });
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.BookCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BookConditions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "As new",
                            IsActive = true,
                            Name = "Excellent"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Minor signs of wear",
                            IsActive = true,
                            Name = "Very Good"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Average wear",
                            IsActive = true,
                            Name = "Good"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Significant wear",
                            IsActive = true,
                            Name = "Fair"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Damaged",
                            IsActive = true,
                            Name = "Poor"
                        });
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.BookStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BookStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Available"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Reserved"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Sold"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Archived"
                        });
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "hans.muller@example.de",
                            FirstName = "Hans",
                            IsActive = true,
                            LastName = "Müller"
                        },
                        new
                        {
                            Id = 2,
                            Email = "sophie.dubois@example.fr",
                            FirstName = "Sophie",
                            IsActive = true,
                            LastName = "Dubois"
                        },
                        new
                        {
                            Id = 3,
                            Email = "haruki.tanaka@example.jp",
                            FirstName = "Haruki",
                            IsActive = true,
                            LastName = "Tanaka"
                        },
                        new
                        {
                            Id = 4,
                            Email = "thabo.ndlovu@example.za",
                            FirstName = "Thabo",
                            IsActive = true,
                            LastName = "Ndlovu"
                        },
                        new
                        {
                            Id = 5,
                            Email = "isabella.fernandez@example.ar",
                            FirstName = "Isabella",
                            IsActive = true,
                            LastName = "Fernandez"
                        });
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.DeliveryAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressAlias")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AddressLine2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("DeliveryAddresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressAlias = "Home",
                            AddressLine1 = "Unter den Linden 77",
                            City = "Berlin",
                            Country = "Germany",
                            CustomerId = 1,
                            PostalCode = "10117"
                        },
                        new
                        {
                            Id = 2,
                            AddressAlias = "Home",
                            AddressLine1 = "15 Avenue des Champs-Élysées",
                            City = "Paris",
                            Country = "France",
                            CustomerId = 2,
                            PostalCode = "75008"
                        },
                        new
                        {
                            Id = 3,
                            AddressAlias = "Home",
                            AddressLine1 = "4-2-8 Shinjuku, Shinjuku-ku",
                            City = "Tokyo",
                            Country = "Japan",
                            CustomerId = 3,
                            PostalCode = "160-0022"
                        },
                        new
                        {
                            Id = 4,
                            AddressAlias = "Home",
                            AddressLine1 = "123 Nelson Mandela Boulevard",
                            City = "Cape Town",
                            Country = "South Africa",
                            CustomerId = 4,
                            PostalCode = "8001"
                        },
                        new
                        {
                            Id = 5,
                            AddressAlias = "Home",
                            AddressLine1 = "789 Avenida 9 de Julio",
                            City = "Buenos Aires",
                            Country = "Argentina",
                            CustomerId = 5,
                            PostalCode = "C1043"
                        });
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique()
                        .HasFilter("[ApplicationUserId] IS NOT NULL");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Jane",
                            HireDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Bob",
                            HireDate = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "New",
                            HireDate = new DateTime(2023, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            LastName = "Unlinked"
                        });
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Levels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Manages store operations",
                            IsActive = true,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Handles sales and customer interactions",
                            IsActive = true,
                            Name = "Sales"
                        });
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("DeliveryAddressId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryAddressId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 1,
                            EmployeeId = 2,
                            OrderDate = new DateTime(2025, 4, 12, 16, 22, 15, 64, DateTimeKind.Utc).AddTicks(1597),
                            OrderStatusId = 1,
                            PaymentMethodId = 2
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 3,
                            DeliveryAddressId = 3,
                            EmployeeId = 2,
                            OrderDate = new DateTime(2025, 4, 10, 16, 22, 15, 64, DateTimeKind.Utc).AddTicks(1603),
                            OrderStatusId = 6,
                            PaymentMethodId = 1
                        });
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "New"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Processing"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Shipped"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Delivered"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Cancelled"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Payment Pending"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Paid"
                        });
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PaymentMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Credit Card"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Cash"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = false,
                            Name = "PayPal"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = false,
                            Name = "Bank Transfer"
                        });
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("WorkSchedule")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LevelId = 1,
                            Title = "Store Manager",
                            WorkSchedule = 0
                        },
                        new
                        {
                            Id = 2,
                            LevelId = 2,
                            Title = "Sales Associate",
                            WorkSchedule = 0
                        });
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.PositionHistory", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PromotionId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PositionId");

                    b.ToTable("PositionHistories");

                    b.HasData(
                        new
                        {
                            PromotionId = 1,
                            EmployeeId = 1,
                            IsActive = true,
                            PositionId = 1,
                            StartDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PromotionId = 2,
                            EmployeeId = 2,
                            IsActive = true,
                            PositionId = 2,
                            StartDate = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PromotionId = 3,
                            EmployeeId = 3,
                            IsActive = true,
                            PositionId = 2,
                            StartDate = new DateTime(2023, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(9, 2)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("EventId");

                    b.HasIndex("OrderId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookId = 1,
                            OrderId = 1,
                            SalePrice = 750.00m
                        },
                        new
                        {
                            Id = 2,
                            BookId = 2,
                            OrderId = 2,
                            SalePrice = 1200.00m
                        },
                        new
                        {
                            Id = 3,
                            BookId = 8,
                            OrderId = 2,
                            SalePrice = 950.00m
                        });
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.SaleEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4, 2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SaleEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Discount = 0.15m,
                            EndDate = new DateTime(2023, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Spring Sale",
                            StartDate = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.SalesAuditLog", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventId"));

                    b.Property<string>("ColumnName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Login")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.ToTable("SalesAuditLogs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.Book", b =>
                {
                    b.HasOne("AntiqueBookstore.Domain.Entities.BookCondition", "Condition")
                        .WithMany("Books")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AntiqueBookstore.Domain.Entities.BookStatus", "Status")
                        .WithMany("Books")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Condition");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.BookAuthor", b =>
                {
                    b.HasOne("AntiqueBookstore.Domain.Entities.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AntiqueBookstore.Domain.Entities.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.DeliveryAddress", b =>
                {
                    b.HasOne("AntiqueBookstore.Domain.Entities.Customer", "Customer")
                        .WithMany("DeliveryAddresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.Employee", b =>
                {
                    b.HasOne("AntiqueBookstore.Domain.Entities.ApplicationUser", "ApplicationUser")
                        .WithOne("Employee")
                        .HasForeignKey("AntiqueBookstore.Domain.Entities.Employee", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.Order", b =>
                {
                    b.HasOne("AntiqueBookstore.Domain.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AntiqueBookstore.Domain.Entities.DeliveryAddress", "DeliveryAddress")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryAddressId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AntiqueBookstore.Domain.Entities.Employee", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AntiqueBookstore.Domain.Entities.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AntiqueBookstore.Domain.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany("Orders")
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("DeliveryAddress");

                    b.Navigation("Employee");

                    b.Navigation("OrderStatus");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.Position", b =>
                {
                    b.HasOne("AntiqueBookstore.Domain.Entities.Level", "Level")
                        .WithMany("Positions")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Level");
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.PositionHistory", b =>
                {
                    b.HasOne("AntiqueBookstore.Domain.Entities.Employee", "Employee")
                        .WithMany("PositionHistories")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AntiqueBookstore.Domain.Entities.Position", "Position")
                        .WithMany("PositionHistories")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.Sale", b =>
                {
                    b.HasOne("AntiqueBookstore.Domain.Entities.Book", "Book")
                        .WithMany("Sales")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AntiqueBookstore.Domain.Entities.SaleEvent", "SaleEvent")
                        .WithMany("Sales")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AntiqueBookstore.Domain.Entities.Order", "Order")
                        .WithMany("Sales")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Order");

                    b.Navigation("SaleEvent");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AntiqueBookstore.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AntiqueBookstore.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AntiqueBookstore.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AntiqueBookstore.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.BookCondition", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.BookStatus", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.Customer", b =>
                {
                    b.Navigation("DeliveryAddresses");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.DeliveryAddress", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("PositionHistories");
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.Level", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.Order", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.PaymentMethod", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.Position", b =>
                {
                    b.Navigation("PositionHistories");
                });

            modelBuilder.Entity("AntiqueBookstore.Domain.Entities.SaleEvent", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
