using AntiqueBookstore.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AntiqueBookstore.Data.Configurations
{
    public class BookConfiguration : IEntityTypeConfiguration<Book>
    {
        // configure the Books entity
        public void Configure(EntityTypeBuilder<Book> builder)
        {
            // Set table name
            //builder.ToTable("Books");

            // Set primary key
            builder.HasKey(b => b.Id); // UNDO: named PK

            // PK autogenerated (autoincrement by default for int)
            builder.Property(b => b.Id).ValueGeneratedOnAdd();

            // Set properties
            builder.Property(b => b.Title)
                .IsRequired()
                .HasMaxLength(255);

            builder.Property(b => b.Publisher)
                .HasMaxLength(100)
                .IsRequired(false);

            builder.Property(b => b.PublicationDate)
                .IsRequired();
            // TODO: Validation for range (1600-2099) to do at the application level

            // Precision for decimal properties
            builder.Property(b => b.PurchasePrice)
                   .HasPrecision(9, 2)
                   .IsRequired(false);
                    // alternative to [Column] attribute

            builder.Property(b => b.RecommendedPrice)
                   .HasPrecision(9, 2)
                   .IsRequired(false);

            // Relation to BookCondition
            builder.HasOne(b => b.Condition)
                   .WithMany(bc => bc.Books)
                   .HasForeignKey(b => b.ConditionId)
                   .OnDelete(DeleteBehavior.Restrict); // Cannot delete Condition if there are Books

            // Relation to BookStatus
            builder.HasOne(b => b.Status)
                   .WithMany(bs => bs.Books)
                   .HasForeignKey(b => b.StatusId)
                   .OnDelete(DeleteBehavior.Restrict); // Cannot delete Status if there are Books

            // Seed data
            builder.HasData(
                new Book
                {
                    Id = 1,
                    Title = "A Study in Scarlet",
                    Publisher = "Ward Lock & Co",
                    PublicationDate = 1887,
                    PurchasePrice = 150.00m,
                    RecommendedPrice = 750.00m,
                    ConditionId = 3, 
                    StatusId = 2
                }
            );
        }
    }
}
