using AntiqueBookstore.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace AntiqueBookstore.Data.Configurations
{
    public class BookConfiguration : IEntityTypeConfiguration<Book>
    {
        // configure the Books entity
        public void Configure(EntityTypeBuilder<Book> builder)
        {
            // Set table name
            //builder.ToTable("Books");

            // Set primary key
            builder.HasKey(b => b.Id); // UNDO: named PK

            // PK autogenerated (autoincrement by default for int)
            builder.Property(b => b.Id).ValueGeneratedOnAdd();

            // Set properties
            builder.Property(b => b.Title)
                .IsRequired()
                .HasMaxLength(255);

            builder.Property(b => b.Publisher)
                .HasMaxLength(100)
                .IsRequired(false);

            builder.Property(b => b.PublicationDate)
                .IsRequired();
            // TODO: Validation for range (1600-2099) to do at the application level

            // Precision for decimal properties
            builder.Property(b => b.PurchasePrice)
                   .HasPrecision(9, 2)
                   .IsRequired(false);
                    // alternative to [Column] attribute

            builder.Property(b => b.RecommendedPrice)
                   .HasPrecision(9, 2)
                   .IsRequired(false);

            builder.Property(b => b.CoverImagePath)
                   .HasMaxLength(255) // MAX_PATH
                   .IsRequired(false);

            // Relation to BookCondition
            builder.HasOne(b => b.Condition)
                   .WithMany(bc => bc.Books)
                   .HasForeignKey(b => b.ConditionId)
                   .OnDelete(DeleteBehavior.Restrict); // Cannot delete Condition if there are Books

            // Relation to BookStatus
            builder.HasOne(b => b.Status)
                   .WithMany(bs => bs.Books)
                   .HasForeignKey(b => b.StatusId)
                   .OnDelete(DeleteBehavior.Restrict); // Cannot delete Status if there are Books

            // Seed data
            builder.HasData(
                new Book
                {
                    Id = 1,
                    Title = "A Study in Scarlet",
                    Publisher = "Ward Lock & Co",
                    PublicationDate = 1887,
                    PurchasePrice = 150.00m,
                    RecommendedPrice = 750.00m,
                    ConditionId = 3, 
                    StatusId = 2
                },
                new Book
                {
                    Id = 2,
                    Title = "The Tale of Genji",
                    Publisher = "Imperial Court of Japan",
                    PublicationDate = 1021,
                    PurchasePrice = 3500.00m,
                    RecommendedPrice = 12000.00m,
                    ConditionId = 2,
                    StatusId = 1
                },
                new Book
                {
                    Id = 3,
                    Title = "A Madman's Diary",
                    Publisher = "New Youth Magazine",
                    PublicationDate = 1918,
                    PurchasePrice = 800.00m,
                    RecommendedPrice = 2500.00m,
                    ConditionId = 1,
                    StatusId = 1
                },
                new Book
                {
                    Id = 4,
                    Title = "The Cairo Trilogy: Palace Walk",
                    Publisher = "American University in Cairo Press",
                    PublicationDate = 1956,
                    PurchasePrice = 450.00m,
                    RecommendedPrice = 1800.00m,
                    ConditionId = 2,
                    StatusId = 1
                },
                new Book
                {
                    Id = 5,
                    Title = "Things Fall Apart",
                    Publisher = "William Heinemann Ltd.",
                    PublicationDate = 1958,
                    PurchasePrice = 1200.00m,
                    RecommendedPrice = 4500.00m,
                    ConditionId = 3,
                    StatusId = 1
                },
                new Book
                {
                    Id = 6,
                    Title = "Ficciones",
                    Publisher = "Editorial Sur",
                    PublicationDate = 1944,
                    PurchasePrice = 900.00m,
                    RecommendedPrice = 3200.00m,
                    ConditionId = 1,
                    StatusId = 1
                },
                new Book
                {
                    Id = 7,
                    Title = "The Master and Margarita",
                    Publisher = "YMCA Press",
                    PublicationDate = 1967,
                    PurchasePrice = 1500.00m,
                    RecommendedPrice = 5800.00m,
                    ConditionId = 2,
                    StatusId = 1
                },
                new Book
                {
                    Id = 8,
                    Title = "Ulysses",
                    Publisher = "Shakespeare and Company",
                    PublicationDate = 1922,
                    PurchasePrice = 4800.00m,
                    RecommendedPrice = 18000.00m,
                    ConditionId = 2,
                    StatusId = 1
                },
                new Book
                {
                    Id = 9,
                    Title = "One Hundred Years of Solitude",
                    Publisher = "Editorial Sudamericana",
                    PublicationDate = 1967,
                    PurchasePrice = 1200.00m,
                    RecommendedPrice = 4500.00m,
                    ConditionId = 1,
                    StatusId = 1
                },
                new Book
                {
                    Id = 10,
                    Title = "The Name of the Rose",
                    Publisher = "Bompiani",
                    PublicationDate = 1980,
                    PurchasePrice = 600.00m,
                    RecommendedPrice = 2200.00m,
                    ConditionId = 1,
                    StatusId = 1
                },
                new Book
                {
                    Id = 11,
                    Title = "Gitanjali",
                    Publisher = "India Society of London",
                    PublicationDate = 1912,
                    PurchasePrice = 2200.00m,
                    RecommendedPrice = 7500.00m,
                    ConditionId = 3,
                    StatusId = 1
                }
            );
        }
    }
}
